name: resite
channels:
  - conda-forge
  - defaults
dependencies:
  - bottleneck
  - cdsapi
  - dask
  - matplotlib
  - Pyomo
  - scipy
  - toolz
  - xarray
  - geopandas
  - cartopy
  - pyyaml
  - xlrd
  - tqdm
  - joblib
  - geopy
  - pypsa
  - shapely